### ISSUE TITLE
android_packages_apps_exTHmSettings/src/com/exthm/settings/fragments/LockScreenSettings.java

### ISSUE THREAD

**Issue by chiajiaen** [exthmui/android_packages_apps_exTHmSettings#2]
packages/apps/exTHmSettings/src/com/exthm/settings/fragments/LockScreenSettings.java:64: error: cannot find symbol
                Settings.System.FINGERPRINT_SUCCESS_VIB, 1) == 1));
                               ^
  symbol:   variable FINGERPRINT_SUCCESS_VIB
  location: class System
packages/apps/exTHmSettings/src/com/exthm/settings/fragments/LockScreenSettings.java:74: error: cannot find symbol
                    Settings.System.FINGERPRINT_SUCCESS_VIB, value ? 1 : 0);
                                   ^
  symbol:   variable FINGERPRINT_SUCCESS_VIB
  location: class System

**Comment by atmouse-** [comment]
Commit reset in 215219e4fb...f9a8810514
