### ISSUE TITLE
packages/apps/exTHmSettings/src/com/exthm/settings/fragments/PowerMenuSettings.java

### ISSUE THREAD

**Issue by chiajiaen** [exthmui/android_packages_apps_exTHmSettings#3]
packages/apps/exTHmSettings/src/com/exthm/settings/fragments/PowerMenuSettings.java:67: error: cannot find symbol
                Settings.System.POWERMENU_TORCH, 0) == 1));
                               ^
  symbol:   variable POWERMENU_TORCH
  location: class System
packages/apps/exTHmSettings/src/com/exthm/settings/fragments/PowerMenuSettings.java:76: error: cannot find symbol
                    Settings.System.POWERMENU_TORCH, value ? 1 : 0);
                                   ^
  symbol:   variable POWERMENU_TORCH
  location: class System
4 errors

**Comment by atmouse-** [comment]
Duplicate of #2
